version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      
      
     
  build:
    commands:
      # - cd /codebuild/output/src4254396729/src/test2
      - mkdir new
      - cd new
      - touch achintha.txt
      - echo "Hi I'm Sankha" > achintha.txt
      
      
      

artifacts:
  files:
    - '**/*'
