version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - apt-get update -y
     
  build:
    commands:
      - echo Downloading the .zip file from S3...
      - sudo mkdir test
      - sudo mkdir test2
      - cd test
      - touch test.txt
      - echo "Hi I'm Sankha" > test.txt
      - cd ..
      - cd test2
      - touch test2.txt
      - echo "Hi I'm Sankha" > test2.txt
      - cd /home/ubuntu
      - sudo mkdir abcd
     

artifacts:
  files:
    - '**/*'
