version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - cd /home/ubuntu
     
  build:
    commands:
      - echo Downloading the .zip file from S3...
      - pwd
      - sudo mkdir abcd
      - cd abcd
      - touch abcd.txt
      - echo "Hi I'm Sankha" > abcd.txt
      
      
      

artifacts:
  files:
    - '**/*'
